In [1]:
import numpy as np
import pickle
import tqdm ## Generate Progress-bar
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout, Activation
import os

In [2]:
sequence_length = 50
FILE_PATH = "wonderland.txt"
BASENAME = os.path.basename(FILE_PATH)
seed = "CHAPTER I" ## Start of Predicting

In [3]:
char2int = pickle.load(open(f"{BASENAME}-char2int.pickle", "rb"))
int2char = pickle.load(open(f"{BASENAME}-int2char.pickle", "rb"))
vocab_size = len(char2int)

In [4]:
## Build The Model
model = Sequential([
    LSTM(256, input_shape=(sequence_length, vocab_size), return_sequences=True),
    Dropout(0.3),
    LSTM(256),
    Dense(vocab_size, activation="softmax"),
])

In [6]:
## load The Optimal Weights
model.load_weights(f"./results/{BASENAME}-{sequence_length}.h5")

In [11]:
s = seed
n_chars = 50

## generate 400 characters
generated = ""
for i in tqdm.tqdm(range(n_chars), "Generating text"):
    # make the input sequence
    X = np.zeros((1, sequence_length, vocab_size))
    print(X)
    for t, char in enumerate(seed):
        X[0, (sequence_length - len(seed)) + t, char2int[char]] = 1 ## [0, (50-9)+0_(i), ]
        
    ## Predict The Next Character
    predicted = model.predict(X, verbose=0)[0]
    
    ## Converting The Vector To an integer
    next_index = np.argmax(predicted)
    # Converting The integer To a character
    next_char = int2char[next_index]
    
    # add the character to results
    generated += next_char
    # shift seed and the predicted character
    seed = seed[1:] + next_char

print("Seed:", s)
print("Generated text:", generated)

Generating text:   0%|                                                                          | 0/50 [00:00<?, ?it/s]

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


KeyError: 'C'